<?php
   include_once("class/class_buch.php");
   $buc = new Buch();
   $lag = new Lagerort();
   $log->log("book-info.php","Execute App",__FILE__,__LINE__);
   $bildurl = test_input(post("bildurl")) ? test_input(post("bildurl")) : "http://localhost/zend/sig/istockphoto-495477978-170667a.jpg";
   $signatur = test_input(post("send"));
   if (test_input(post("signatur"))) $signatur = test_input(post("signatur"));
   if (!$signatur) $signatur = $_COOKIE["signatur"];
   setcookie("signatur",$signatur,time+3600);
   $sql = "SELECT * FROM buch WHERE signatur='".$signatur."'";
   if (!$res = $buc->exec($sql,__FILE__,__LINE__)) $buc->error(__FILE__,__LINE__);
   if ($row = $res->fetch_assoc()) {
      $buc->id             = $row["id"];
      $buc->signatur       = $row["signatur"];
      $buc->titel          = $row["titel"];
      $buc->autor          = $row["autor"];
      $buc->herausgeber    = $row["herausgeber"];
      $buc->kategorie      = $row["kategorie"];
      $buc->verlag         = $row["verlag"];
      $buc->ort            = $row["ort"];
      $buc->reihe          = $row["reihe"];
      $buc->band           = $row["band"];
      $buc->jahr           = $row["jahr"];
      $buc->monat          = $row["monat"];
      $buc->lagerort       = $row["lagerort"];
      $buc->isbn           = $row["isbn"];
      $buc->bestellcode    = $row["bestellcode"];
      $buc->klappentext    = $row["klappentext"];
      $buc->anschaffung    = $row["anschaffung"];
      $buc->preis          = $row["preis"];
      $buc->wert           = $row["wert"];
      $buc->sprache        = $row["sprache"];
      $buc->einband        = $row["einband"];
      $buc->bildurl        = $row["bildurl"];
      $lag->_update($buc->lagerort);
   } else die("Interner Fehler in php/book-info-p01.php Zeile 9");
   $id = test_input(post("id")) ? test_input(post("id")) : $buc->id;
   $titel = test_input(post("titel")) ? test_input(post("titel")) : $buc->titel;
   $autor = test_input(post("autor")) ? test_input(post("autor")) : $buc->autor;
   $herausgeber = test_input(post("herausgeber")) ? test_input(post("herausgeber")) : $buc->herausgeber;
   $kategorie = test_input(post("kategorie")) ? test_input(post("kategorie")) : $buc->kategorie;
   $verlag = test_input(post("verlag")) ? test_input(post("verlag")) : $buc->verlag;
   $ort = test_input(post("ort")) ? test_input(post("ort")) : $buc->ort;
   $reihe = test_input(post("reihe")) ? test_input(post("reihe")) : $buc->reihe;
   $band = test_input(post("band")) ? test_input(post("band")) : $buc->band;
   $jahr = test_input(post("jahr")) ? test_input(post("jahr")) : $buc->jahr;
   $monat = test_input(post("monat")) ? test_input(post("monat")) : $buc->monat;
   $lagerort = test_input(post("lagerort")) ? test_input(post("lagerort")) : $buc->lagerort;
   $isbn = test_input(post("isbn")) ? test_input(post("isbn")) : $buc->isbn;
   $bestellcode = test_input(post("bestellcode")) ? test_input(post("bestellcode")) : $buc->bestellcode;
   $klappentext = test_input(post("klappentext")) ? test_input(post("klappentext")) : $buc->klappentext;
   $anschaffung = test_input(post("anschaffung")) ? test_input(post("anschaffung")) : $buc->anschaffung;
   $preis = test_input(post("preis")) ? test_input(post("preis")) : $buc->preis;
   $wert = test_input(post("wert")) ? test_input(post("wert")) : $buc->wert;
   $sprache = test_input(post("sprache")) ? test_input(post("sprache")) : $buc->sprache;
   $einband = test_input(post("einband")) ? test_input(post("einband")) : $buc->einband;
   $bildurl = test_input(post("bildurl")) ? test_input(post("bildurl")) : $buc->bildurl;
   $lag->_update($lagerort);
   $s_kategorie = "SELECT kategorie FROM rkategorie ORDER BY kategorie";
   $r_kategorie = r_option($sql=$s_kategorie,$name="kategorie",$field="kategorie",$def1=$kategorie,$tab="4",$ronly=true);
   $s_sprache   = "SELECT sprache, lang FROM rsprache ORDER BY lang";
   $r_sprache   = r_select_option($sql=$s_sprache,$name="sprache",$field="lang",$def1=$sprache,$tab="18",$ronly=true);
   $s_einband   = "SELECT einband FROM reinband ORDER BY einband";
   $r_einband   = r_option($sql=$s_einband,$name="einband",$field="einband",$def1=$einband,$tab="19",$ronly=true);
   $s_lagerort  = "SELECT lagerort FROM rlagerort ORDER BY lagerort";
   $r_lagerort  = r_option($sql=$s_lagerort,$name="lagerort",$field="lagerort",$def1=$lagerort,$tab="11",$ronly=true);
?> 
